### ISSUE TITLE
AlloyDB Provider has "PUBLIC" ip_type hardcoded, making it impossible to configure it with PRIVATE one

### ISSUE THREAD

**Issue by jk-kashe** [GoogleCloudPlatform/genai-databases-retrieval-app#422]
in retrieval_service/datastore/providers/alloydb.py, line 65, ip_type is hardcoded.

It should be moved to config, so that configuration can specify PRIVATE or PUBLIC type.

**Comment by Yuan325** [comment]
In order to use the alloydb-python-connector, this provider is configured to use AlloyDB's Public IP. For AlloyDB private ip, please refer to the datastore/providers/postgres.py that does not use the alloydb-python-connector (or documentations here: https://github.com/GoogleCloudPlatform/genai-databases-retrieval-app/blob/main/docs/datastore/postgres.md).

Feel free to reopen if this does not resolve your issue. Thank you!
